server:
  context-path: /
  port: 8000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp